Feature/message select
cocoide/commitify pull request #14
Opened 2023-09-02 13:46 UTC by cocoide

2023-09-02 15:44 UTC, mochi-yu requested changes

2023-09-02 15:44 UTC, mochi-yu commented on internal/service/message.go
> +}
この関数自体はasyncじゃない？
37行目の`strings.Split(<-result, "\n")`で、チャンネルからの受信を待機しているので、全体としては同期しているのかなと思います。

2023-09-02 15:44 UTC, mochi-yu commented on internal/service/message.go
> +func (s *messageService) AsyncGenerateCommitMessage() ([]string, error) {
関数名が`GenerateCommitMessage`などの方が良いかなと思います。

2023-09-02 15:44 UTC, mochi-yu commented on cmd/suggest.go
> +		messages, err := ms.AsyncGenerateCommitMessage()
関数名の変更 `GenerateCommitMessage`

2023-09-02 15:48 UTC, cocoide commented on internal/service/message.go
> +}
元々は非同期だったけど仕様を変えて名前も変えるの忘れてたすまない

2023-09-02 16:24 UTC, cocoide commented
@mochi-yu 
すまん、あっちのブランチ間違えて消してしまったから、クラスの名前の意図を伝えるとあえて抽象的にしたのは他にもMessage系のServiceを作る可能性があってその度Service作るの面倒くさいなと思ったから。
命名はすぐ変えれるし最初はシンプルでいいかなと思った。
MessageGenerateServiceとかでもいいのかなと思ってる。

2023-09-03 08:43 UTC, mochi-yu commented
@cocoide コンフリクトが起きてるので、そこの対処はできる？

2023-09-03 09:36 UTC, merged