loading完成
cocoide/commitify pull request #25
Opened 2023-09-04 15:43 UTC by Akira0809

#4
手元で試せないので動くはわかりません。
多分できてるはず、、

2023-09-04 17:02 UTC, mochi-yu commented
これ、参考にしたサイトとかあります？

2023-09-04 17:10 UTC, mochi-yu requested changes

2023-09-04 17:10 UTC, mochi-yu commented on cmd/suggest.go
> +		}
77行目にある通り、これは`msg := msg.(type)`で場合分けしていて、メッセージの種類に関するswitch文。
ただ、74行目の`case tea.Cmd:`はコマンドの種類で場合分けしてしまっているので、この74から77までの条件はずっと呼ばれていないかなーって感じ。

ちなみに、コマンドは、新しいメッセージを作る関数みたいなものらしい。

参照：https://zenn.dev/tbistr/articles/ce4e838bbd2ec3
流れは、**コマンド**がボタン操作とかキー操作とか、その他のイベントを受けつけて、**メッセージ**を生成。
その**メッセージ**を**Update**が受け取って、**メッセージ**の動作に応じて動作、**モデル**を更新する。
**モデル**が更新されると、それに応じて**View**を更新、みたいな流れ

2023-09-04 17:11 UTC, mochi-yu commented
デフォルトでロードの実装があるかもしれない…。
https://github.com/charmbracelet/bubbles#spinner

2023-09-05 03:05 UTC, Akira0809 commented on cmd/suggest.go
> +		}
どうすればいいかな？
ChatGPTに聞いて調べて実装みたいな感じでしてるから、

2023-09-05 04:20 UTC, mochi-yu commented on cmd/suggest.go
> +		}
switch文のdefaultで更新処理を書くか、一番簡単なのは下に載せた参考実装を見ながらカスタムすることかなと思うけど…

2023-09-07 15:32 UTC, cocoide commented on cmd/suggest.go
> +		}
main関数に  isLoadingの時だけtime.tickかfor文とsleep使って、animationIndexを切り替える処理入れたらいけると思う。

2023-09-10 05:40 UTC, closed without merging