アーキテクチャ構成の修正案
cocoide/commitify pull request #59
Opened 2023-10-05 15:54 UTC by cocoide

2023-10-05 15:58 UTC, cocoide commented
毎回homeのconfを参照する件は、うまいことconfの情報をどこかにcacheできないのかなと思いつつ

2023-10-05 15:59 UTC, cocoide commented
log.Fatalは
os.Exit(1)を含むので
その後の処理は考えなくていいよ

2023-10-05 16:04 UTC, cocoide commented
serviceではconfの読み込みはしないというルールを設けてる

2023-10-05 17:16 UTC, cocoide commented
ローカルでのメッセージ切り替え完了。
DI元を切り替えることで実装。

2023-10-11 13:08 UTC, mochi-yu requested changes
恐らく議論できるだけの十分な知識は持ち合わせていないので、自分は他の用事も多くあまりコミットできないので、大島さんのこの構成で進めてもらって構いません。

2023-10-11 13:08 UTC, mochi-yu commented on internal/gateway/grpc.go
grpcのクラインアントの処理関数も`github.com/cocoide/commitify-grpc-server/pkg/pb`から参照してるのは、サーバのリポジトリからクライアントの関数参照しているのは個人的には気持ち悪いなと思うけど…。

2023-10-11 13:08 UTC, mochi-yu commented on internal/service/service.go
> +}
GitHubではなくて、単なるGitじゃない？

2023-10-11 13:09 UTC, mochi-yu commented on internal/gateway/grpc.go
根拠を持ってダメとは言えないので、変えるか変えないかはお任せします。

2023-10-11 13:18 UTC, cocoide commented on internal/gateway/grpc.go
理想はgrpc専用のrepoを使ったほうがいいかな。それは面倒だから
一旦、internalとpkgと区別してるから内部ロジックではないと区別はした感じ。

2023-10-11 13:22 UTC, cocoide commented on internal/gateway/input_output.go
これをGitGatewayにしようかな
gitコマンドを操作してる感じだし

2023-10-11 13:22 UTC, cocoide commented on cmd/config.go
> +		{int(entity.Server), int(entity.Local)},
たしかに、修正する！

2023-10-16 11:51 UTC, cocoide commented on internal/service/service.go
> +}
GithubがGitを包括するって意味で言いたかった!
でGithubServiceはGithubに関係するロジックをまとめたかったのが意図ではある。
わかりにくければGitにするわ

2023-11-06 12:15 UTC, merged